version: "3.9"
services:
  db:
    image: postgres:10.1
    volumes:
      - tmp-data:/tmp/data/
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  migration:
    image: django-app
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
  web:
    build: .
    image: django-app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - migration
      - db
volumes:
    tmp-data:
        driver: local
    postgresql-data:
        driver: local




